services:
  proxy:
    image: nginx:stable-perl
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - backend
    depends_on:
      - ptvu_be-music

  ptvu_be-music:
    build:
      context: .
      dockerfile: ./musics/Dockerfile
    restart: always
    volumes:
      - ./musics/prod-application.properties:/app/application.properties
    networks:
      - backend
    expose:
      - 8080
    depends_on:
      ptvu_db:
        condition: service_healthy

  ptvu_db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend
    expose:
      - 3306
    volumes:
      - ptvu_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  ptvu_db:

networks:
  backend:
    driver: bridge
