services:
  ptvu-be-music:
    build:
      context: .
      dockerfile: ./musics/Dockerfile
    expose:
      - 8080
    volumes:
      - ./musics/prod-application.properties:/app/application.properties
      - ptvu-musics:/app/musics
    networks:
      - backend
    depends_on:
      ptvu-db:
        condition: service_healthy

  ptvu-be-streaming:
    build:
      context: .
      dockerfile: ./streaming/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ptvu-musics:/app/musics
    networks:
      - backend

  ptvu-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend
    expose:
      - 3306
    volumes:
      - ptvu-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  ptvu-db:
  ptvu-musics:

networks:
  backend:
    driver: bridge
