@startuml VIR1_Project
actor EndUser
participant APIGateway
participant Streaming
participant Musics
database DataBaseEngine

' Get musics
EndUser->APIGateway: /api/musics (GET)
activate APIGateway

APIGateway->Musics
activate Musics

Musics->DataBaseEngine
activate DataBaseEngine

DataBaseEngine->Musics: return the musics
deactivate DataBaseEngine

Musics->APIGateway: return data
deactivate Musics

APIGateway->EndUser: return data
deactivate APIGateway

' Get musics by artist
EndUser->APIGateway: /api/stream/{id} (GET)
activate APIGateway

APIGateway->Streaming
activate Streaming

Streaming->Musics: music={id}
activate Musics

Musics->DataBaseEngine
activate DataBaseEngine

DataBaseEngine->Musics: return the music
deactivate DataBaseEngine

Musics->Streaming: return return the music
deactivate Musics

Streaming->APIGateway: return streaming data
deactivate Streaming

APIGateway->EndUser: return streaming data
deactivate APIGateway
@enduml